### ISSUE TITLE
Newest version (Honoka) not working on Huawei P40 Pro

### ISSUE THREAD

**Issue by ghost** [aeri/Nihonoari-App#42] opened 2022-11-17 19:05 UTC
When I open the latest Release of the app it just stays black and nothing happens on my Huawei P40 Pro. I downloaded it from F-Droid and after that didn't work GitHub. The release before that does work.

**Comment by aeri** [comment] 2022-11-17 21:05
Sorry for the inconvenience, I am aware of this bug, it was a configuration error in the last release after changing the build tools, it is already fixed in the commit https://github.com/aeri/Nihonoari-App/commit/ff0209358042d8efa6125228fecbbadab55bd619 and soon the fix will be updated in F-Droid with revision code 1.7.1.

**Comment by aeri** [comment] 2022-11-17 22:25
In the meantime you can use the APKs in the release that I have published [here](https://github.com/aeri/Nihonoari-App/releases/tag/v1.7.1).

**Comment by aeri** [comment] 2022-11-20 21:53
It is already updated in F-droid and should work on your device correctly.

**Comment by sans-c** [comment] 2022-11-28 12:24
> It is already updated in F-droid and should work on your device correctly.

Hi there,

the issue seems to persist. 1.7.1 (F-droid), black screen and nothing happens. I can't speak to the previous releases. This is the first and only one I tried.

Edit: tried very outdated 1.5 our of curiosity and this one worked.

**Comment by aeri** [comment] 2022-11-28 13:33
What version of Android do you have?

**Comment by sans-c** [comment] 2022-11-28 14:06
I am using the latest LineageOS 18.1 build (Android 11) for my device.

Edit: I just realized you use Flutter. There are known issues with LineageOS eventhough they usually manifest differently. See this [issue](https://github.com/flutter/flutter/issues/105093) for example. I am not quite sure whether this is related or not since for your app the screen just stays black and the original report didn't mention Lineage at all.

**Comment by aeri** [comment] 2022-11-28 14:20
How curious because the system I use is vanilla LineageOS 18.1 and it works perfectly for me, I have also detected that there is a problem with API versions 16 and 19 after bumping the Android Gradle build tools version to 7.3, is being discussed [here](https://github.com/flutter/flutter/issues/115100) and it could be related.

Can you provide some trace with logcat while starting the application?

We can also try to compile with a previous AGP version and see if that fixes the problem.

**Comment by sans-c** [comment] 2022-11-28 14:32
I can't provide logs at the moment, sorry. However I'm willing to try a test build of yours.

Another option would be to wait for a fixed Flutter release. The issue I mentioned is quite long-standing, yours is fresh. Maybe things change. ;) I am in no hurry.

**Comment by aeri** [comment] 2022-12-24 18:05
I have added a new release candidate ([v1.7.2-rc.1](https://github.com/aeri/Nihonoari-App/releases/tag/v1.7.2-rc.1)) based on the commit ae59849d074c93400adf038902ed41af99029480, in which I downgraded the gradle version to 7.2.1, I also set the software rendering (to see if it helps).

I look forward to hearing from you about the results. Hopefully this is it, otherwise I will continue to investigate why it happens.

**Comment by sans-c** [comment] 2022-12-26 22:57
Hey there, no luck here. Just tried the version you mentioned, same symptoms as before. Merry late christmas. :)

btw: app version is reported as 1.7.1 in this release candidate.

**Comment by aeri** [comment] 2022-12-26 23:10
Too bad, thanks for the feedback, then it might require a regression of Flutter as there are no other critical changes I have made to the core of the app. Regarding the APK version I forgot to change it in code so it effectively overlays the previous version.

Without analyzing the crash logs it is difficult to draw any further conclusions, however, are any of the versions after 1.5.0 working for you? 

In v1.6.1 I updated the Flutter SDK to compile with null safety.

P.S.: Merry Christmas to you too and have a happy new year :)

**Comment by sans-c** [comment] 2022-12-26 23:32
1.5.0 F-Droid works with splash screen
1.6.0 (github) works with splash screen
1.6.1 F-Droid surprisingly works but without splash screen
1.7.1 shows a black screen

I suspected Flutter before but since 1.6.1 works (eventhough I am not sure the missing splash screen is intended), it seems unlikely. Strange.

**Comment by aeri** [comment] 2022-12-26 23:53
This case is really interesting. The major change from v1.6.1 to v1.7.1 was the Android Gradle Plugin version, which went from version 4.1.0 to 7.3.1 (7.2.1 in the case of the RC), it really is a severe change in the compilation tool and was required by the F-Droid servers that no longer compiled with an obsolete version of the AGP.

In addition, the issue of Cyrillic input and a scaling of on-screen elements was added, which should not cause any problems.

Therefore it could be inferred that the problem comes from upgrading the Gradle version and at the same time altering the splash screen behavior. I also find it interesting that the application does not close and the stop message is not displayed and only a black screen is shown.

**Comment by aeri** [comment] 2022-12-27 01:46
I have created an empty Flutter project and moved its build configuration to the app, all the changes are in the [new branch](https://github.com/aeri/Nihonoari-App/tree/42-newest-version-honoka-not-working-on-huawei-p40-pro) for testing, I have also removed the splash screen.

I add here for simplicity a .zip with the new build, I have also added the minimal Flutter project (```demo-arm64-v8a-release.apk```) to test if it works .

It would be great if you could test this one too. Thanks.

[nihonoari-v1.7.2-rc.2.zip](https://github.com/aeri/Nihonoari-App/files/10305293/nihonoari-v1.7.2-rc.2.zip)

**Comment by sans-c** [comment] 2022-12-27 09:49
Thanks for your effort. The build from the .zip doesn't work either. Black screen, nothing happens. I could test your demo-build if you provided an arm-v7 one. :)

**Comment by aeri** [comment] 2022-12-27 23:51
Thanks to you for your collaboration :)

Sorry, I didn't attach for ARMv7, I pass it to you here, this is an empty Flutter example project that features a minimal screen and a configuration that I used as a base for the APK I passed above, if this version works it will give us enough information about where the problem could be.

I attach it here: [demo-armeabi-v7a-release.zip](https://github.com/aeri/Nihonoari-App/files/10311198/demo-armeabi-v7a-release.zip)

**Comment by sans-c** [comment] 2022-12-28 00:08
Seems to work. Flutter Demo Home Page with a clickable button and working counter. :)

heads-up: I will likely be unable to respond the next few days.

**Comment by aeri** [comment] 2023-01-08 18:13
What an interesting behavior, it is a good starting point to try to correct the problem, with this result I tend to think that it is not a problem in app build but in my code.

**Comment by aeri** [comment] 2023-01-31 04:08
I have created a new version with Flutter version 3.7.0, I have also removed practically all the assets except for the translation ones to see if there is any problem with their loading, I have also got rid of all the external packages. In fact the application is not functional.

Since I can't see the error logs, there is no other way than trial and error, the idea is to test a version of Nihonoari with the minimum structure and from there to restore functionality to see where the problem arises. 

I was encouraged to know that the default application was working correctly. It would be great if you could test these versions.

I add also the generic app built with the new version of Flutter.

[builds-apk.zip](https://github.com/aeri/Nihonoari-App/files/10542622/builds-apk.zip)

**Comment by aeri** [comment] 2023-04-14 13:20
I have uploaded a new version that fixes several bugs related to the application startup, it is already available now on F-Droid, could you please confirm me if everything works fine? Thanks

**Comment by sans-c** [comment] 2023-04-14 13:28
> I have uploaded a new version that fixes several bugs related to the application startup, it is already available now on F-Droid, could you please confirm me if everything works fine? Thanks

I can! It works flawlessly from what I can tell! :) Sorry for my long abscence. Glad to see you managed to fix this without further input. Out of curiosity: can you share what the culprit was? I see virtually the same issue in another app, but haven't reached out to them yet. Not sure if the cause is the same.

Good work, thanks!

**Comment by aeri** [comment] 2023-04-14 16:23
Great, thank you for confirming this, we can finally close this issue.

In this case there were two reasons why the application crashed at startup:

If German or Belarusian was used as language on the device, the app tried to apply those translations but they were wrongly assigned and the app could not start.

In versions prior to Android 5 the problem was caused by using AGP >= 7.3.1, the Flutter team is investigating the cause.

**Closed as completed by aeri** 2023-04-14 16:23 UTC
